# Generated by Django 2.2 on 2020-10-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='dealer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owner',
                to='accounts.Dealer'),
        ),
    ]
