# Generated by Django 2.2 on 2020-10-13 10:21

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201013_1006'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts.managers.AccountManager()),
            ],
        ),
    ]
