# Generated by Django 2.2 on 2020-10-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201013_1021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('email',)},
        ),
    ]
