# Generated by Django 2.2 on 2020-10-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201013_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotter',
            name='location',
        ),
    ]
