# Generated by Django 2.2 on 2020-10-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_plotter_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_dealer',
            field=models.BooleanField(default=False, verbose_name='Dealer'),
        ),
    ]
