# Generated by Django 2.2 on 2020-10-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201014_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='users',
            field=models.ManyToManyField(blank=True, to='accounts.User'),
        ),
    ]
